addSbtPlugin("org.playframework" % "sbt-plugin" % "3.0.8")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.17.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.3.0")
addSbtPlugin("nl.gn0s1s" % "sbt-dotenv" % "3.1.1")
addSbtPlugin("io.github.play-swagger" % "sbt-play-swagger" % "2.0.0")